version: '3.8'
services:
  rabbitmq:
    container_name: "mq_dev"
    image: rabbitmq:3-management
    ports:
      - '5672:5672'     # AMQP protocol port
      - '15672:15672'   # HTTP management UI
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - ./data:/Users/joeylam/dev/rabbitmq/data:rw
      - ./rabbitmq.config:/Users/joeylam/dev/rabbitmq/conf/rabbitmq.config:ro
volumes:
  rabbitmq_data:
    driver: local